spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          leet:
            issuer-uri: http://localhost:8002
        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
          leet:
            provider: leet
            client-id: leet
            client-secret: pass
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8002/login/oauth2/code/leet
            scope:
              - openid
server:
  port: 8000
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
